development:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username: sbCobJcyoon1
  password: d43faf48-6b15-4c14-aa37-61a74127dd72
  register_users: false

test:
  base_url: https://rest.developer.yodlee.com/services/srest/restserver/v1.0
  username:
  password:
  register_users: false

production:
  base_url:
  username:
  password:
  register_users: true
